# This file was generated by GoReleaser. DO NOT EDIT.
cask "tm" do
  name "tm"
  desc "Trade crypto from your terminal"
  homepage "https://github.com/true-markets/cli"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tm"

  on_macos do
    on_intel do
      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_darwin_amd64.tar.gz"
      sha256 "7247f04df9016b0c6ef044c24cfc2dfd2a942ada34730cd62426f41fbb14bbc7"
    end
    on_arm do
      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_darwin_arm64.tar.gz"
      sha256 "8bdbd9c16c246e8bd8cb20f480088110387a94007450fb06cb44787ee48642b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_linux_amd64.tar.gz"
      sha256 "0d8fc4a2e4adea5c5ac38a5c76f60ce859d2e4c473afca89c66c232dbbe1fc03"
    end
    on_arm do
      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_linux_arm64.tar.gz"
      sha256 "a987cadb97faf62dceba2bf83e1dcb7b00425774568ad72617ef5261b0e070f1"
    end
  end

  # No zap stanza required
end
