# This file was generated by GoReleaser. DO NOT EDIT.
cask "tm" do
  version "0.0.10"

  on_macos do
    on_intel do
      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_darwin_amd64.tar.gz"
      sha256 "16601a020abb423c0805c6d35e5f16fdbb521a3bdfb65fc3ec5a27b4dc6a80de"
    end
    on_arm do
      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_darwin_arm64.tar.gz"
      sha256 "59ce44b16344adb3d438762c2ec85af6c0b0c1cd8123b9b52f8ba77b1295d90b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_linux_amd64.tar.gz"
      sha256 "8001b476f7e797947f76124642c7d9ed01ba912f1f379cd61cd6b200ea929bd0"
    end
    on_arm do
      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_linux_arm64.tar.gz"
      sha256 "fa58a8c2492875a42a927dc2d92e6ed72e5e48c85f004dae49ab4570439f1361"
    end
  end

  name "tm"
  desc "Trade crypto from your terminal"
  homepage "https://github.com/true-markets/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tm"

  # No zap stanza required

end
