# This file was generated by GoReleaser. DO NOT EDIT.
cask "tm" do
  version "0.0.9"

  on_macos do
    on_intel do
      sha256 "3d81f7b35ff62f99f749b2d39a60279d4727baa951273e0353f90c2ed4fd62c5"

      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fe79ecad57ce912ec7a87d2f4003400e6b1b49a999592b39d4e2f4b78affa57"

      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "df44703e64aee51aa85f6312af4bb778c6e0d434ac313daaa9847d9136c95bc8"

      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3a55f8dc26025eeb2c2c589b54ec7c2488f56ef94b50c81e23ca91033a54fe6"

      url "https://github.com/true-markets/cli/releases/download/v#{version}/tm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tm"
  desc "Trade crypto from your terminal"
  homepage "https://github.com/true-markets/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tm"

  # No zap stanza required
end
